# Generated by Django 2.1.5 on 2019-03-19 12:31

from django.db import migrations


def add_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='author')
    Group.objects.get_or_create(name='editor')
    Group.objects.get_or_create(name='chief')


def delete_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.filter(name='author').delete()
    Group.objects.filter(name='editor').delete()
    Group.objects.filter(name='chief').delete()


class Migration(migrations.Migration):

    dependencies = [
        ('sesam', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_groups, delete_groups),
    ]
