# Generated by Django 2.1.5 on 2019-03-06 15:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sesam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='boss',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Boss'),
        ),
    ]
