# Generated by Django 2.1.5 on 2019-03-19 12:31

from django.db import migrations

from ..models import USER_GROUPS


def add_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    for group in USER_GROUPS:
        Group.objects.get_or_create(name=group.title())


def delete_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    for group in USER_GROUPS:
        Group.objects.filter(name__iexact=group).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('sesam', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_groups, delete_groups),
    ]
