# Generated by Django 2.1.5 on 2019-03-19 21:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('sesam', '0002_add_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='game',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='gamesetting',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='gamesetting',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='question',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='question',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='room',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='room',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='updated at'),
        ),
        migrations.AlterField(
            model_name='usermoneylogmodel',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='created at'),
        ),
        migrations.AlterField(
            model_name='usermoneylogmodel',
            name='updated_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='updated at'),
        ),
    ]
