# Generated by Django 2.1.5 on 2019-03-29 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesam', '0002_add_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedquestioncategory',
            name='date',
            field=models.DateField(null=True, verbose_name='assignment date'),
        ),
    ]
