# Generated by Django 2.1.5 on 2019-03-19 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesam', '0003_auto_20190320_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
