# Generated by Django 2.1.5 on 2019-04-06 02:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sesam', '0003_questioncategory_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='sesam.QuestionCategory', verbose_name='question category'),
        ),
    ]
