# Generated by Django 2.1.5 on 2019-03-23 12:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('sesam', '0004_question_reviewed_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignedQuestionCategory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='id')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('created_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='created at')),
                ('updated_at', models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='updated at')),
                ('date', models.DateField(verbose_name='assignment date')),
            ],
        ),
        migrations.AlterField(
            model_name='questioncategory',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddField(
            model_name='assignedquestioncategory',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sesam.QuestionCategory', verbose_name='category'),
        ),
        migrations.AddField(
            model_name='assignedquestioncategory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_categories', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AddField(
            model_name='questioncategory',
            name='assigned_users',
            field=models.ManyToManyField(through='sesam.AssignedQuestionCategory', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='assignedquestioncategory',
            unique_together={('user', 'date', 'category')},
        ),
    ]
