# Generated by Django 2.1.5 on 2019-02-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesam', '0004_auto_20190228_1614'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='points',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='usermoneylogmodel',
            name='points',
            field=models.BooleanField(default=False),
        ),
    ]
