# Generated by Django 2.1.5 on 2019-02-28 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sesam', '0005_auto_20190228_1641'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='started_at',
            field=models.DateTimeField(null=True),
        ),
    ]
